import {
  ArrowRight,
  ArrowUpRight,
  BadgeCheck,
  Banknote,
  Barcode,
  Bell,
  Boxes,
  Building2,
  Calendar,
  ChartColumn,
  Check,
  ChevronDown,
  ChevronRight,
  CircleCheck,
  ClipboardList,
  Clock,
  CreditCard,
  Download,
  FileText,
  Gem,
  HeartHandshake,
  IndianRupee,
  Layers,
  Lock,
  Mail,
  MapPin,
  Menu,
  Minus,
  Monitor,
  Package,
  Percent,
  Phone,
  Pill,
  Plus,
  Printer,
  QrCode,
  Receipt,
  ReceiptIndianRupee,
  RefreshCcw,
  ScanBarcode,
  Search,
  ShieldCheck,
  ShoppingBasket,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Store,
  Tag,
  Timer,
  TrendingUp,
  TriangleAlert,
  Truck,
  UserRound,
  Users,
  UtensilsCrossed,
  Wallet,
  X,
  Zap,
  type LucideIcon,
} from 'lucide-react'

const ICONS = {
  'arrow-right': ArrowRight,
  'arrow-up-right': ArrowUpRight,
  'badge-check': BadgeCheck,
  banknote: Banknote,
  barcode: Barcode,
  bell: Bell,
  boxes: Boxes,
  building: Building2,
  calendar: Calendar,
  chart: ChartColumn,
  check: Check,
  'chevron-down': ChevronDown,
  'chevron-right': ChevronRight,
  'circle-check': CircleCheck,
  clipboard: ClipboardList,
  clock: Clock,
  card: CreditCard,
  download: Download,
  file: FileText,
  gem: Gem,
  handshake: HeartHandshake,
  rupee: IndianRupee,
  layers: Layers,
  lock: Lock,
  mail: Mail,
  pin: MapPin,
  menu: Menu,
  minus: Minus,
  monitor: Monitor,
  package: Package,
  percent: Percent,
  phone: Phone,
  pill: Pill,
  plus: Plus,
  printer: Printer,
  qr: QrCode,
  receipt: Receipt,
  'gst-receipt': ReceiptIndianRupee,
  refresh: RefreshCcw,
  scan: ScanBarcode,
  search: Search,
  shield: ShieldCheck,
  basket: ShoppingBasket,
  cart: ShoppingCart,
  phone2: Smartphone,
  sparkles: Sparkles,
  store: Store,
  tag: Tag,
  timer: Timer,
  trend: TrendingUp,
  alert: TriangleAlert,
  truck: Truck,
  user: UserRound,
  users: Users,
  utensils: UtensilsCrossed,
  wallet: Wallet,
  close: X,
  zap: Zap,
} satisfies Record<string, LucideIcon>

export type IconName = keyof typeof ICONS

interface IconProps {
  name: IconName
  className?: string
  size?: number
  strokeWidth?: number
}

/** Decorative icon (hidden from assistive tech). Pair with visible text or an aria-label on the parent. */
export function Icon({ name, className, size = 20, strokeWidth = 1.9 }: IconProps) {
  const Cmp = ICONS[name]
  return <Cmp aria-hidden="true" focusable="false" className={className} width={size} height={size} strokeWidth={strokeWidth} />
}
